version: "3"
services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  node-api:
    build:
      context: .
      args:
        - DATABASE_URL=postgresql://postgres:mysecretpassword@localhost:5432/contaacc?schema=public
    ports:
      - 3000:3000
    depends_on:
      - redis
      - db

volumes:
  redis:
  postgres:
